### ISSUE TITLE
Builders might be better off using Object.defineProperty

### ISSUE THREAD

**Issue by mattfbacon** [OlexG/Patterns#2]
In case you don't want these attributes (that would probably be present in a class) to be, e.g., enumerable, you can use [Object.defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) with `enumerable: false`. There is also a read-only attribute, as well as getters and setters.

**Comment by mattfbacon** [comment]
This applies to `Creational/builder.js`.

**Comment by OlexG** [comment]
yeah but in this case, it's fine if they are enumerable and changeable though thanks for the suggestion, I did not know about the defineProperty method. I think builder.js demonstrates the essence of builder pattern fine with or without it.

**Comment by mattfbacon** [comment]
It's just that a class with the same fields wouldn't be enumerable so since you're trying to simulate multiple inheritance (at least from what I can tell) it's not actually the same thing.
