### ISSUE TITLE
Object creators should probably be static?

### ISSUE THREAD

**Issue by mattfbacon** [OlexG/Patterns#3]
A function to create an instance doesn't really make sense as an instance method, unless that method makes a clone of the existing instance. Same is true if you are just going to take an instance of something else.

General rule: if you don't need access to instance-specific data, don't make it an instance method.

```ts
abstract class UserCreator {
	abstract createUser(): User

	printWelcomeMessage(user: User) {
		console.log(user.getWelcomeMessage());
	}
}
```

to

```ts
abstract class UserCreator {
	static abstract createUser(): User

	static printWelcomeMessage(user: User) {
		console.log(user.getWelcomeMessage());
	}
}
```

and

```ts
function someClientFunction(creator: UserCreator) {
	// is not aware of creator type
	const user = creator.createUser();
	creator.printWelcomeMessage(user);
}

someClientFunction(new AdminCreator());
someClientFunction(new CustomerCreator());
```

to

```ts
function someClientFunction(creator: typeof UserCreator) {
	// is not aware of creator type
	const user = creator.createUser();
	creator.printWelcomeMessage(user);
}

someClientFunction(AdminCreator);
someClientFunction(CustomerCreator);
```

**Comment by mattfbacon** [comment]
This applies to `Creational/factoryMethod.ts`

**Comment by OlexG** [comment]
You cannot make that class static. It makes a user instance (unique to object) and implements methods relating to that specific instance.

**Comment by mattfbacon** [comment]
The user is not static but the user creator is.

**Comment by mattfbacon** [comment]
If you want to have the creators depend on instance fields, then add instance fields to demonstrate this.

**Comment by OlexG** [comment]
just realized I can't do abstract static so sadly no static
